Repository UCLALibrary/ursus, pull requests merged in 2018-11, with the labels that each got.

#107 Fix facet display
  app/assets/stylesheets/ursus.scss
  app/assets/stylesheets/ursus/_body.scss
  app/assets/stylesheets/ursus/_facets.scss
Labels: in progress

#115 Renamed files so specs will be run as part of the suite.
  spec/features/facet_labels_spec.rb
  spec/features/genre_display_spec.rb
Labels: review

#126 Remove extra border around header
  app/assets/stylesheets/ursus/_navbar.scss
Labels: review

#127 Fixed spec that was broken after merge
  spec/features/facet_labels_spec.rb
Labels: review

#128 Use sassc-rails instead of sass-rails
  Gemfile
  Gemfile.lock
Labels: review

#130 Links to individual records from the home page. Story #124
  app/helpers/home_page_helper.rb
  app/views/catalog/_image_grid.html.erb
  spec/helpers/home_page_helper_spec.rb
  spec/rails_helper.rb
  spec/support/solr_helpers.rb
Labels: review

#132 Revert "Use sassc-rails instead of sass-rails"
  Gemfile
  Gemfile.lock
Labels: review

#133 Links to the individual featured works from the home page. Story #124
  app/helpers/home_page_helper.rb
  app/views/catalog/_image_grid.html.erb
  config/blacklight.yml
  spec/helpers/home_page_helper_spec.rb
  spec/rails_helper.rb
  spec/support/solr_helpers.rb
Labels: review

#134 Removed uneven borders. Story #120
  app/assets/stylesheets/ursus/_image_grid.scss
  app/views/catalog/_image_grid.html.erb
Labels: review

#139 Change feedback link styles to have a tad less pop
  app/assets/stylesheets/ursus/_feedback_link.scss
  app/assets/stylesheets/ursus/_footer.scss
Labels: review

#143 Insert basic google analytics
  app/views/layouts/application.html.erb
Labels: review

#147 Add close feedback functionality
  app/assets/javascripts/feedback.js
  app/assets/stylesheets/ursus/_colors.scss
  app/assets/stylesheets/ursus/_feedback_link.scss
  app/views/shared/_footer.html.erb
Labels: review

#148 Support for deploying tagged releases to stage server via jenkins
  .travis.yml
Labels: devops, review

#151 Modification of encrypted URL for tagged releases via jenkins
  .travis.yml
Labels: review

#152 Encrypted URL modification 2
  .travis.yml
Labels: review

#155 URL Modification 3
  .travis.yml
Labels: review

#156 URL modification 4
  .travis.yml
Labels: review

#157 URL modification 5
  .travis.yml
Labels: review

#146 remove app/views/layouts/application.html.erb
  app/views/layouts/application.html.erb
Labels: review

#161 fix stray javascript
  app/views/shared/_footer.html.erb
Labels: review

#160 'Cite' becomes 'Cite This Item'
  config/locales/blacklight.en.yml
  spec/features/view_work_spec.rb
Labels: review
